import xlsxwriter
from mimetypes import MimeTypes
import urllib.request

null = "null"

individual_stats = [
    {
      "participation": 0,
      "user_id": 3945,
      "deskercises_change": 0,
      "leaderboard_hash": "9319b39ff3e1697ca8d58664fc5cec70a86efdc5",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:users-in-challenge|time_mode:0|S|user_id:3945|group_id:0|team_id:0|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 234,
      "display_name": "yack",
      "continent_id": 3,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": 1439,
      "engaged_user_change": 0,
      "trait_categories": [
        1
      ],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e516fb0dd093ae8b7ce2c0",
      "region_id": 512,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:10:35.267Z",
      "team_id": 0,
      "stat_hash": "1ae167c847ed3e7d85c1f30cf702e43f342e688d",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:users-in-challenge|time_mode:0|",
      "image_user_profile_url": "https://d2qqvi7evhy56u.cloudfront.net/8a9b9996da72bd42906f36dd6e7f9890f6bbabd1.png",
      "time_value": "",
      "city_id": 20018,
      "avg_user_mets_output_change": 0,
      "occupation_id": 1850,
      "rank": 1,
      "title": "yack",
      "steps": 0,
      "traits": [
        1850
      ],
      "activities_change": 0,
      "occupation_title": "Onboarding Specialist",
      "location_title": "Preston, GB",
      "time_mode": 0,
      "distance": 20264.096,
      "met_minutes": 1225.1862449378577,
      "company_title": "Somerset Associations",
      "engaged_user_count": 0,
      "duration": 6901,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 0
    },
    {
      "participation": 0,
      "user_id": 3206,
      "deskercises_change": 0,
      "leaderboard_hash": "9319b39ff3e1697ca8d58664fc5cec70a86efdc5",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:users-in-challenge|time_mode:0|S|user_id:3206|group_id:0|team_id:0|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 235,
      "display_name": "Pat Hitchins",
      "continent_id": 5,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": 1108,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e516fb0dd093ae8b7ce2c1",
      "region_id": 194,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:10:35.267Z",
      "team_id": 0,
      "stat_hash": "0854a7ad0d11208a9b68e0485f0e9a75aa4794b3",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:users-in-challenge|time_mode:0|",
      "image_user_profile_url": "http://files.parse.com/90e2a6b4-00dc-47dc-aa9a-22fb389dd836/4d675470-d898-4f35-bbd8-589e6132d0f2-Screen%20Shot%202013-12-02%20at%2012.05.13%20PM.jpg",
      "time_value": "",
      "city_id": 14009,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 2,
      "title": "Pat Hitchins",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": "Austin, TX, US",
      "time_mode": 0,
      "distance": 5956.3,
      "met_minutes": 307.98,
      "company_title": "FitRankings",
      "engaged_user_count": 0,
      "duration": 1566,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 44
    },
    {
      "participation": 0,
      "user_id": 3603,
      "deskercises_change": 0,
      "leaderboard_hash": "9319b39ff3e1697ca8d58664fc5cec70a86efdc5",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:users-in-challenge|time_mode:0|S|user_id:3603|group_id:0|team_id:0|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 235,
      "display_name": "Mark Ragan",
      "continent_id": 5,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": null,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e516fb0dd093ae8b7ce2c2",
      "region_id": 194,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:10:35.267Z",
      "team_id": 0,
      "stat_hash": "e931c1dad34be19a625bfb57b3b9e81dd593ece3",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:users-in-challenge|time_mode:0|",
      "image_user_profile_url": "",
      "time_value": "",
      "city_id": 14009,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 3,
      "title": "Mark Ragan",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": null,
      "time_mode": 0,
      "distance": 0,
      "met_minutes": 0,
      "company_title": null,
      "engaged_user_count": 0,
      "duration": 0,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 44
    }
  ]

team_stats = [
    {
      "participation": 0,
      "user_id": 0,
      "deskercises_change": 0,
      "leaderboard_hash": "1ba309053728eb737979213b44db87703b4d708e",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|S|user_id:0|group_id:0|team_id:534|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 0,
      "display_name": "",
      "continent_id": 0,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": null,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e51de9f65fe8aa8b0f8737",
      "region_id": 0,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:40:09.250Z",
      "team_id": 534,
      "stat_hash": "3cc25056c9984be3337c13f50044aff12365bb4c",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|",
      "image_user_profile_url": "",
      "time_value": "",
      "city_id": 0,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 1,
      "title": "New Team1",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": null,
      "time_mode": 0,
      "distance": 26220.396,
      "met_minutes": 1533.1662449378578,
      "company_title": null,
      "engaged_user_count": 0,
      "duration": 8467,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 0
    },
    {
      "participation": 0,
      "user_id": 0,
      "deskercises_change": 0,
      "leaderboard_hash": "1ba309053728eb737979213b44db87703b4d708e",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|S|user_id:0|group_id:0|team_id:504|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 0,
      "display_name": "",
      "continent_id": 0,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": null,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e51de9f65fe8aa8b0f8738",
      "region_id": 0,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:40:09.250Z",
      "team_id": 504,
      "stat_hash": "e6375be8c6b5f566a2519ff6a3945c4a97b4110c",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|",
      "image_user_profile_url": "",
      "time_value": "",
      "city_id": 0,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 2,
      "title": "testing",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": null,
      "time_mode": 0,
      "distance": 0,
      "met_minutes": 0,
      "company_title": null,
      "engaged_user_count": 0,
      "duration": 0,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 0
    },
    {
      "participation": 0,
      "user_id": 0,
      "deskercises_change": 0,
      "leaderboard_hash": "1ba309053728eb737979213b44db87703b4d708e",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|S|user_id:0|group_id:0|team_id:505|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 0,
      "display_name": "",
      "continent_id": 0,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": null,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e51de9f65fe8aa8b0f8739",
      "region_id": 0,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:40:09.250Z",
      "team_id": 505,
      "stat_hash": "20d2210aba062969b928acb562b16d5aeb95a62d",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|",
      "image_user_profile_url": "",
      "time_value": "",
      "city_id": 0,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 3,
      "title": "testing",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": null,
      "time_mode": 0,
      "distance": 0,
      "met_minutes": 0,
      "company_title": null,
      "engaged_user_count": 0,
      "duration": 0,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 0
    },
    {
      "participation": 0,
      "user_id": 0,
      "deskercises_change": 0,
      "leaderboard_hash": "1ba309053728eb737979213b44db87703b4d708e",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|S|user_id:0|group_id:0|team_id:506|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 0,
      "display_name": "",
      "continent_id": 0,
      "rank_change": 0,
      "score": 0,
      "mets_change": 0,
      "company_id": null,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e51de9f65fe8aa8b0f873a",
      "region_id": 0,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:40:09.250Z",
      "team_id": 506,
      "stat_hash": "1a45983dd8bb77bbb0d2bef936680710c95912f6",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|",
      "image_user_profile_url": "",
      "time_value": "",
      "city_id": 0,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 4,
      "title": "testing",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": null,
      "time_mode": 0,
      "distance": 0,
      "met_minutes": 0,
      "company_title": null,
      "engaged_user_count": 0,
      "duration": 0,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 0
    },
    {
      "participation": 0,
      "user_id": 0,
      "deskercises_change": 0,
      "leaderboard_hash": "1ba309053728eb737979213b44db87703b4d708e",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|S|user_id:0|group_id:0|team_id:507|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 0,
      "display_name": "",
      "continent_id": 0,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": null,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e51de9f65fe8aa8b0f873b",
      "region_id": 0,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:40:09.250Z",
      "team_id": 507,
      "stat_hash": "0bc2606339becf334235e85eab0851fcf804eef7",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|",
      "image_user_profile_url": "",
      "time_value": "",
      "city_id": 0,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 5,
      "title": "testing",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": null,
      "time_mode": 0,
      "distance": 0,
      "met_minutes": 0,
      "company_title": null,
      "engaged_user_count": 0,
      "duration": 0,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 0
    },
    {
      "participation": 0,
      "user_id": 0,
      "deskercises_change": 0,
      "leaderboard_hash": "1ba309053728eb737979213b44db87703b4d708e",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|S|user_id:0|group_id:0|team_id:513|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 0,
      "display_name": "",
      "continent_id": 0,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": null,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e51de9f65fe8aa8b0f873c",
      "region_id": 0,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:40:09.250Z",
      "team_id": 513,
      "stat_hash": "d6937b87c32210e201708f0db92108e39d144291",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|",
      "image_user_profile_url": "",
      "time_value": "",
      "city_id": 0,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 6,
      "title": "Hello",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": null,
      "time_mode": 0,
      "distance": 0,
      "met_minutes": 0,
      "company_title": null,
      "engaged_user_count": 0,
      "duration": 0,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 0
    },
    {
      "participation": 0,
      "user_id": 0,
      "deskercises_change": 0,
      "leaderboard_hash": "1ba309053728eb737979213b44db87703b4d708e",
      "stat_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|S|user_id:0|group_id:0|team_id:521|venue_id:0|",
      "mets": 0,
      "image_main_url": "",
      "full_name": "",
      "expected_user_count": 1,
      "deskercises": 0,
      "distance_change": 0,
      "country_id": 0,
      "display_name": "",
      "continent_id": 0,
      "rank_change": 1,
      "score": 0,
      "mets_change": 0,
      "company_id": null,
      "engaged_user_change": 0,
      "trait_categories": [],
      "group_id": 0,
      "challenge_id": 0,
      "group_name": "",
      "steps_change": 0,
      "met_minutes_change": 0,
      "activities": 0,
      "duration_change": 0,
      "url": "",
      "_id": "58e51de9f65fe8aa8b0f873d",
      "region_id": 0,
      "participation_change": 0,
      "avg_user_mets_output": 0,
      "image_badge_url": "",
      "calculated_at": "2017-04-05T16:40:09.250Z",
      "team_id": 521,
      "stat_hash": "0c17f0f94ed4e72c5878e8200f706467b4d9d61c",
      "leaderboard_hash_debug": "|challenge_id:537|metric:3|rank_context:teams-in-challenge|time_mode:0|",
      "image_user_profile_url": "",
      "time_value": "",
      "city_id": 0,
      "avg_user_mets_output_change": 0,
      "occupation_id": null,
      "rank": 7,
      "title": "Hello",
      "steps": 0,
      "traits": [],
      "activities_change": 0,
      "occupation_title": null,
      "location_title": null,
      "time_mode": 0,
      "distance": 0,
      "met_minutes": 0,
      "company_title": null,
      "engaged_user_count": 0,
      "duration": 0,
      "venue_id": 0,
      "group_type": 0,
      "state_province_id": 0
    }
  ]

workbook = xlsxwriter.Workbook('challenge-results-test.xlsx')
worksheet = workbook.add_worksheet()

worksheet.write('A1', 'Rank')
worksheet.write('B1', 'Name')
worksheet.write('C1', 'Met Minutes')
worksheet.write('D1', 'Steps')
worksheet.write('E1', 'Distance (mi)')
worksheet.write('F1', 'Time (min)')

row = 1
for stat in team_stats:
	distance_miles = stat['distance'] / 1609.34
	time_min = stat['duration'] /60
	export_stats = [
		stat['rank'],
		stat['title'],
		round(stat['met_minutes'], 2),
		round(stat['steps'], 2),
		round(distance_miles, 2),
		round(time_min, 2)
	]
	print(export_stats)
	col = 0
	for item in export_stats:
		worksheet.write(row, col, item)
		col += 1
	row += 1

workbook.close()

mime = MimeTypes()
url = urllib.request.pathname2url('challenge-results-test.xlsx')
type = mime.guess_type(url)
print(type)
